name: Sync to Hugging Face Hub

on:
  push:
    branches: [main, master]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install Hugging Face Hub CLI
        run: pip install -U "huggingface_hub[cli]"

      - name: Upload Repo to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config lfs.allowincompletepush || true
          git remote rm origin || true
          git push https://arifsoul:$HF_TOKEN@huggingface.co/spaces/arifsoul/sign_language_translator main  